config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {
      sessions: "users/sessions"
    }

    resources :mailings, only: %i[index] do
      collection do
        patch :update_settings, to: "mailings#update_settings", as: 'update_settings'
        get :settings, to: "mailings#settings", as: 'settings'
      end
    end

    resources :reports, only: %i[index] do
      collection do
        get :users, to: "reports#users_reports", as: 'users'
      end
    end

    resources :orders, except: %i[edit update] do
      collection do
        get :archive
        post 'create_for_product/:product_id', to: 'orders#create_for_product', as: :create_for_product
        delete 'delete_last', to: 'orders#delete_last', as: :delete_last
        get 'users', to: 'orders#users', as: :users
      end
    end
    resources :categories, except: %i[show edit update]
    resources :products do
      collection do
        get :archive
      end
      member do
        patch :restore
        delete :really_destroy
      end
    end

    resources :users, except: %i[new create] do
      member do
        patch :restore
        delete :really_destroy
        patch :approve

        get 'payment', to: 'user_payments#payment', as: 'payment'
        post 'payment/deposit_money', to: 'user_payments#deposit_money', as: 'deposit_money'
        post 'payment/pay_all_orders', to: 'user_payments#pay_all_orders', as: 'pay_all_orders'
        post 'payment/pay_order/:id', to: 'user_payments#pay_order', as: 'pay_order'
      end
      collection do
        get :requests
        get :archive
        patch :approve_all
        delete :delete_all
      end
    end

    resources :store, only: [:index], controller: 'telegram/store'

    # Маршруты для аутентификации через Telegram
    resource :telegram_session, only: [:new, :create], controller: 'telegram/sessions'

    telegram_webhook Telegram::TelegramWebhooksController

    # Defines the root path route ("/")
    root to: 'telegram/store#index'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  acts_as_paranoid

  has_one :users_role, -> { with_deleted }, dependent: :destroy, inverse_of: :user
  has_one :role, through: :users_role
  has_many :orders, dependent: :destroy
  has_many :payments, through: :orders

  validates :username, presence: true, uniqueness: true
  validates :telegram_chat_id, presence: true, uniqueness: true
  validates :deposit, numericality: { greater_than_or_equal_to: 0 }

  scope :filter_by_username, ->(name) { where('username ILIKE :query', query: "%#{name}%") }
  scope :filter_by_date, ->(start_date, end_date) { where(orders: { created_at: start_date..end_date }) }
  scope :filter_by_state, ->(state) { joins(:orders).merge(Order.filter_by_state(state)) }
  scope :approved, -> { where(approve: true) }
  scope :unapproved, -> { where(approve: false) }

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end

  def approve!
    update!(approve: true)
  end

  def admin?
    role.name == 'admin'
  end

  def manager?
    role.name == 'manager'
  end

  def admin_or_manager?
    admin? || manager?
  end

  def count_orders
    orders.count
  end

  def summarize_orders_price
    orders.includes(:payment).sum('payments.amount')
  end

  def self.create_user_telegram(telegram_username:, telegram_chat_id:)
    role = Role.find_by(name: 'user')

    User.transaction do
      user = create!(telegram_username:,
                     telegram_chat_id:,
                     username: telegram_username,
                     password: Devise.friendly_token)
      UsersRole.create!(user:, role:)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource param_method: :user_params
  before_action :set_user, only: %i[edit update approve]
  before_action :find_deleted_user, only: %i[show restore destroy really_destroy]

  def index
    @users = User.filter_by_username(params[:search_query]).approved.includes(:role).page(params[:page]).per(10)
  end

  def requests
    @users = User.unapproved.page(params[:page])
  end

  def archive
    @users = User.only_deleted.includes(:role).page(params[:page])

    render 'index'
  end

  def show; end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      update_user_role
      update_user_attributes
    end

    redirect_to user_url(@user), notice: t('.success_updated')

  rescue
    render :edit, status: :unprocessable_entity
  end

  def destroy
    if @user.destroy
      TelegramService.after_rejection(chat_id: @user.telegram_chat_id)
      redirect_to users_path, notice: t('.success')
    else
      render :show
    end
  end

  def restore
    if @user.restore
      redirect_to user_url(@user), notice: t('.success')
    else
      render :show, status: :unprocessable_entity
    end
  end

  def really_destroy
    if @user.really_destroy!
      redirect_to archive_users_path, notice: t('.success')
    else
      render archive_users_path, status: :unprocessable_entity
    end
  end

  def approve
    if @user.approve!
      TelegramService.after_approve(chat_id: @user.telegram_chat_id)
      redirect_to requests_users_path, notice: t('.success')
    else
      render :index, status: :unprocessable_entity
    end
  end

  def approve_all
    @users = User.unapproved
    if @users.update_all(approve: true)
      @users.each { |user| TelegramService.after_approve(chat_id: user.telegram_chat_id) }
      redirect_to requests_users_path, notice: t('.success')
    else
      render requests_users_path, notice: t('.no_users')
    end
  end

  def delete_all
    @users = User.unapproved
    if @users.unapproved.destroy_all
      @users.each do |user|
        user.approve = false
        TelegramService.after_rejection(chat_id: user.telegram_chat_id)
        TelegramService.hide_web_app_button(chat_id: user.telegram_chat_id)
      end
      redirect_to requests_users_path, notice: t('.success')
    else
      redirect_to requests_users_path, notice: t('.no_users')
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def find_deleted_user
    @user = User.with_deleted.find(params[:id])
  end

  def user_params
    params.require(:user).permit(current_ability.permitted_attributes(:update, @user))
  end

  def update_user_role
    @user.role = Role.find(user_params[:role_id])
  end

  def update_user_attributes
    attrs = user_params.except(:role_id)

    if attrs[:password].present? && !@user.admin_or_manager?
      @user.errors.add(:password, :not_authorized)
      return false
    end

    if attrs[:password].blank?
      @user.update_without_password(attrs)
    else
      @user.update(attrs)
    end
  end
end

app/views/users/_nav.html.slim
ul.nav.nav-tabs.mb-4
  li.nav-item
    = active_link_to t('.active'), users_path, class: 'nav-link link-dark'
  li.nav-item.position-relative
    = active_link_to requests_users_path, class: 'nav-link link-dark' do
      = t('.users_requests')
      - if User.unapproved.count > 0
        span.position-absolute.top-10.start-100.translate-middle.badge.rounded-pill.bg-danger style="font-size: 0.7em;"
          = User.unapproved.count
  li.nav-item
    = active_link_to t('.archive'), archive_users_path, class: 'nav-link link-dark'

app/views/users/edit.html.slim
= link_to t('global.button.back'), user_path(@user), class: 'btn btn-secondary mb-2'

h2 = t('.edit_profile')

= render 'shared/errors', object: @user

= form_with model: @user do |f|
  .mb-3.row
    .col-sm-2.col-form-label
      = f.label :username

    .col-sm-10
      = f.text_field :username, class: 'form-control form-control-lg'

  .mb-3.row
    .col-sm-2.col-form-label
      = f.label :deposit

    .col-sm-10
      = f.text_field :deposit, class: 'form-control form-control-lg'

  .mb-3.row
    .col-sm-2.col-form-label
      = f.label :approve

    .col-sm-10
      = f.select :approve, [["approve", true], ["unapproved", false]] , { selected: @user.approve },
              class: 'form-select form-select-lg'
  - if can?(:update, @user, :role_id)
    .mb-3.row
      .col-sm-2.col-form-label
        = f.label :role_id

      .col-sm-10
        = f.collection_select :role_id, Role.all, :id, :name, { selected: @user.role.id },
                class: 'form-select form-select-lg'

  - if can?(:update, @user, :password) && @user.admin_or_manager?
    .mb-3.row
      .col-sm-2.col-form-label
        = f.label :password

      .col-sm-10
        = f.password_field :password, class: 'form-control form-control-lg'

    .mb-3.row
      .col-sm-2.col-form-label
        = f.label :password_confirmation

      .col-sm-10
        = f.password_field :password_confirmation,
                class: 'form-control form-control-lg'

  = f.submit t('global.button.save'), class: 'btn btn-primary'

app/views/users/index.html.slim
h1.mb-3 = t('navigation.users')

= render 'nav'

= turbo_frame_tag 'users' do
  = render template: 'users/users'

app/views/users/requests.html.slim
h1.mb-3 = t('navigation.users')

= render 'nav'

.btn-group
  = link_to t('.connect_all_users'), approve_all_users_path, class: 'btn btn-secondary',
          data: { turbo_method: :patch }
  = link_to t('.delete_all_users'), delete_all_users_path, class: 'btn btn-danger',
          data: { turbo_method: :delete, confirm: t('global.dialog.you_sure') }

table.table.table-striped.table-hover.mt-2
  thead
    th scope="col" = t('activerecord.attributes.user.id')
    th scope="col" = t('activerecord.attributes.user.username')
    th scope="col" = t('activerecord.attributes.user.telegram_chat_id')
    th scope="col" = t('activerecord.attributes.user.created_at')
    th scope="col"
  tbody
    - @users.each do |user|
      tr
        th scope="row" =< user.id
        td = link_to user.decorate.name_with_sign, user_path(user), data: { turbo_frame: '_top' }
        td = user.telegram_chat_id
        td = l(user.created_at, format: :medium)
        td
          .btn-group
            = link_to t('.connect'), approve_user_path(user), class: 'btn btn-secondary', data: { turbo_method: :patch }
            = link_to t('global.button.delete'), user_path(user), class: 'btn btn-danger',
                    data: { turbo_method: :delete, confirm: t('global.dialog.you_sure') }

.d-flex.justify-content-center.mt-3
  = paginate @users

app/views/users/show.html.slim
= link_to t('global.button.back'), users_path, class: 'btn btn-secondary mb-2', data: { turbo_frame: '_top' }

h1.mb-4
  = @user.decorate.name_with_sign
.row
  .col-md-8
    .user-info
      - scope = 'activerecord.attributes.user'
      - user_data = { t('username', scope: scope) => @user.username,
                      t('.telegram_username', scope: scope) => @user.telegram_username,
                      t('.chat_id', scope: scope) => @user.telegram_chat_id,
                      t('.debt', scope: scope) => @user.deposit,
                      t('.deposit', scope: scope) => @user.deposit,
                      t('.role', scope: scope) => @user.role.name }

      - user_data.each do |label, value|
        .row.mb-2
          .col-6
            span = label
          .col-6.text-right
            = value

  .col-md-4.d-flex.justify-content-center
    .user-actions.d-flex.flex-column.w-auto
      - if @user.deleted_at
        = link_to t('global.button.restore'), restore_user_path(@user), data: { turbo_method: :patch }, class: 'btn btn-primary mb-1'
        = link_to t('global.button.really_delete'), really_destroy_user_path(@user), class: 'btn btn-primary',
                data: { turbo_method: :delete, confirm: t('global.dialog.you_sure'), turbo_frame: '_top' }
      - else
        = link_to t('global.button.edit'), edit_user_path(@user), class: 'btn btn-primary mb-1',
                data: { turbo_stream: true }
        = link_to t('global.button.payed'), '#', class: 'btn btn-primary mb-1', method: :patch
        - if can? :delete, User
          = link_to t('global.button.delete'), user_path(@user), class: 'btn btn-danger mb-1',
                    data: { turbo_method: :delete, confirm: t('global.dialog.you_sure') }

app/views/users/users.html.slim
= render 'shared/filter', path: users_path if current_page?(users_path)

- scope = 'activerecord.attributes.user'
table.table.table-striped.table-hover.mt-2
  thead
    th scope="col" = t('id', scope: scope)
    th scope="col" = t('username', scope: scope)
    th scope="col" = t('telegram_chat_id', scope: scope)
    th scope="col" = t('created_at', scope: scope)
  tbody
    - @users.each do |user|
      tr
        th scope="row" =< user.id
        td = link_to highlight(user.decorate.name_with_sign, params[:search_query]),
                user_path(user), data: { turbo_frame: '_top' }
        td = user.telegram_chat_id
        td = l(user.created_at, format: :medium)

.d-flex.justify-content-center.mt-3
  = paginate @users