config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {
      sessions: "users/sessions"
    }

    resources :mailings, only: %i[index] do
      collection do
        patch :update_settings, to: "mailings#update_settings", as: 'update_settings'
        get :settings, to: "mailings#settings", as: 'settings'
      end
    end

    resources :reports, only: %i[index] do
      collection do
        get :users, to: "reports#users_reports", as: 'users'
      end
    end

    resources :orders, except: %i[edit update] do
      collection do
        get :archive
        post 'create_for_product/:product_id', to: 'orders#create_for_product', as: :create_for_product
        delete 'delete_last', to: 'orders#delete_last', as: :delete_last
        get 'users', to: 'orders#users', as: :users
      end
    end
    resources :categories, except: %i[show edit update]
    resources :products do
      collection do
        get :archive
      end
      member do
        patch :restore
        delete :really_destroy
      end
    end

    resources :users, except: %i[new create] do
      member do
        patch :restore
        delete :really_destroy
        patch :approve

        get 'payment', to: 'user_payments#payment', as: 'payment'
        post 'payment/deposit_money', to: 'user_payments#deposit_money', as: 'deposit_money'
        post 'payment/pay_all_orders', to: 'user_payments#pay_all_orders', as: 'pay_all_orders'
        post 'payment/pay_order/:id', to: 'user_payments#pay_order', as: 'pay_order'
      end
      collection do
        get :requests
        get :archive
        patch :approve_all
        delete :delete_all
      end
    end

    resources :store, only: [:index], controller: 'telegram/store'

    # Маршруты для аутентификации через Telegram
    resource :telegram_session, only: [:new, :create], controller: 'telegram/sessions'

    telegram_webhook Telegram::TelegramWebhooksController

    # Defines the root path route ("/")
    root to: 'telegram/store#index'
  end
end

app/views/shared/_errors.html.slim
- if object&.errors.full_messages.any?
  .alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_filter.html.slim
= form_with url: path, method: :get, local: true,
        data: { controller: 'debounce', debounce_target: 'form', turbo_stream: true } do |f|
  .row
    .form-group
      = f.search_field :search_query, value: params[:search_query], placeholder: 'Поиск',
              data: { action: "input->debounce#search" }, class: 'form-control'

app/views/shared/_flash.html.slim
- flash.each do |k, v|
  = tag.div v, class: "alert alert-#{k}", role: 'alert'

app/views/shared/_image_form.html.slim
.dropzone.dropzone-default.dz-clickable data-controller="dropzone" data-dropzone-max-file-size="5" data-dropzone-accepted-files="image/*" data-dropzone-max-files="1" data-upload-multiple="true"
  = form.file_field :image, multiple: false, direct_upload: true, data: { dropzone_target: 'input' }
  .dropzone-msg.dz-message.needsclick
    h3.dropzone-msg-title = t('global.image_form.drag_and_drop')
    span.dropzone-msg-desc = t('global.image_form.size_file')

app/views/shared/_menu.html.slim
.sidebar.d-flex.flex-column.flex-grow-1
  h3.mt-5.mb-5.text-white = t('dana')
  ul.nav.nav-pills.flex-column
    li.nav-item
      = link_to t('navigation.reports'), reports_path, class: 'nav-link'
    li.nav-item
      = link_to users_path, class: 'nav-link position-relative d-inline-block' do
        = t('navigation.users')
        - if User.unapproved.count > 0
          span.position-absolute.top-0.start-100.translate-middle.badge.rounded-pill.bg-danger style="font-size: 0.7em;"
            = User.unapproved.count
    li.nav-item
      = link_to t('navigation.products'), products_path, class: 'nav-link'
    li.nav-item
      = link_to t('navigation.orders'), orders_path, class: 'nav-link'
    li.nav-item
      = link_to t('navigation.mailing'), mailings_url, class: 'nav-link'
  .user-info.mt-auto.mb-5
    ul.nav.col-12.col-lg-auto.mb-2.mb-md-0
      li.dropdown
        = link_to '#', class: 'nav-link dropdown-toggle',
                data: { 'bs-toggle': 'dropdown' } do
          = tag.div '', class: "flag mt-1"
          = t I18n.locale

        ul.dropdown-menu.p-3
          - I18n.available_locales.each do |locale|
            li.px-2
              - if I18n.locale == locale
                = tag.span t(locale), class: 'dropdown-item p-0 text-black'
              - else
                = link_to t(locale), url_for(locale: locale), class: 'dropdown-item p-0 text-black'

    .nav.col-12.col-lg-auto.mb-2.mb-md-0
      - if user_signed_in?
        li.dropdown
          = link_to current_user.decorate.name_with_sign, '#', class: 'nav-link dropdown-toggle',
                  data: { 'bs-toggle': 'dropdown' }

          ul.dropdown-menu
            li = link_to t('navigation.user_profile'), edit_user_registration_path,
                    class: 'dropdown-item px-2 text-black'

            li.dropdown-divider

            li = button_to t('navigation.log_out'), destroy_user_session_path,
                    class: 'dropdown-item px-2 text-black', method: :delete