config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {
      sessions: "users/sessions"
    }

    resources :mailings, only: %i[index] do
      collection do
        patch :update_settings, to: "mailings#update_settings", as: 'update_settings'
        get :settings, to: "mailings#settings", as: 'settings'
      end
    end

    resources :reports, only: %i[index] do
      collection do
        get :users, to: "reports#users_reports", as: 'users'
      end
    end

    resources :orders, except: %i[edit update] do
      collection do
        get :archive
        post 'create_for_product/:product_id', to: 'orders#create_for_product', as: :create_for_product
        delete 'delete_last', to: 'orders#delete_last', as: :delete_last
        get 'users', to: 'orders#users', as: :users
      end
    end
    resources :categories, except: %i[show edit update]
    resources :products do
      collection do
        get :archive
      end
      member do
        patch :restore
        delete :really_destroy
      end
    end

    resources :users, except: %i[new create] do
      member do
        patch :restore
        delete :really_destroy
        patch :approve

        get 'payment', to: 'user_payments#payment', as: 'payment'
        post 'payment/deposit_money', to: 'user_payments#deposit_money', as: 'deposit_money'
        post 'payment/pay_all_orders', to: 'user_payments#pay_all_orders', as: 'pay_all_orders'
        post 'payment/pay_order/:id', to: 'user_payments#pay_order', as: 'pay_order'
      end
      collection do
        get :requests
        get :archive
        patch :approve_all
        delete :delete_all
      end
    end

    resources :store, only: [:index], controller: 'telegram/store'

    # Маршруты для аутентификации через Telegram
    resource :telegram_session, only: [:new, :create], controller: 'telegram/sessions'

    telegram_webhook Telegram::TelegramWebhooksController

    # Defines the root path route ("/")
    root to: 'telegram/store#index'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid

  belongs_to :category
  has_many :orders, dependent: :destroy
  has_one_attached :image, dependent: :destroy do |photo|
    photo.variant :preview, resize_to_fill: [200, 150], preprocessed: true
  end

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :filter_by_product, ->(product) { where(name: product) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource param_method: :product_params
  before_action :set_product, only: %i[edit update]
  before_action :set_product_with_deleted, only: %i[show restore destroy really_destroy]

  def index
    @products = Product.includes(:category).page(params[:page]).per(12)
  end

  def archive
    @products = Product.includes(:category).only_deleted.page(params[:page]).per(14)
    render 'index'
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        flash.now[:success] = t('.success')
        format.html { redirect_to product_url(@product), notice: t('.success') }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.remove(:modal),
            turbo_stream.prepend('flash', partial: 'shared/flash')
          ]
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: t('.success') }
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.remove(:modal),
            turbo_stream.prepend('flash', partial: 'shared/flash'),
          ]
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @product.destroy!
      redirect_to products_url, notice: t('.success')
    else
      render :show, status: :unprocessable_entity
    end
  end

  def restore
    if @product.restore
      redirect_to product_path(@product), notice: t('.success')
    else
      render :show
    end
  end

  def really_destroy
    if @product.really_destroy!
      redirect_to products_url, notice: t('.success')
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_product_with_deleted
    @product = Product.with_deleted.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :quantity, :category_id, :image)
  end
end

app/views/products/_form.html.slim
= render 'shared/errors', object: @product

= form_with model: @product do |f|
  .mb-3.row
    .col-sm-2.col-form-label
      = f.label :name

    .col-sm-10
      = f.text_field :name, class: 'form-control form-control-lg'

  .mb-3.row
    .col-sm-2.col-form-label
      = f.label :category_id

    .col-sm-10
      = f.select :category_id, Category.pluck(:name, :id), {class: 'form-select form-select-lg'},
              { data: { controller: 'select' } }

  .mb-3.row
    .col-sm-2.col-form-label
      = f.label :price

    .col-sm-10
      = f.text_field :price, class: 'form-control form-control-lg'

  .mb-3.row
    .col-sm-2.col-form-label
      = f.label :quantity

    .col-sm-10
      = f.text_field :quantity, class: 'form-control form-control-lg'

  .mb-3.row
    = render 'shared/image_form', form: f

  = f.submit t('global.button.save'), class: 'btn btn-primary'

  = link_to t('global.button.close'), '#', data: { controller: 'modal', action: 'modal#close' },
          class: 'btn btn-danger'

app/views/products/_image_form.html.slim
.dropzone.dropzone-default.dz-clickable data-controller="dropzone" data-dropzone-max-file-size="5" data-dropzone-accepted-files="image/*" data-dropzone-max-files="1" data-upload-multiple="true"
  = form.file_field :image, multiple: false, direct_upload: true, data: { dropzone_target: 'input' }
  .dropzone-msg.dz-message.needsclick
    h3.dropzone-msg-title Drag here to upload or click here to browse
    span.dropzone-msg-desc 5 MB file size maximum. Allowed file types png, jpg.

app/views/products/_nav.html.slim
ul.nav.nav-tabs.mb-4
  li.nav-item
    = active_link_to t('.active'), products_path, class: 'nav-link link-dark'
  li.nav-item
    = active_link_to t('.categories'), categories_path, class: 'nav-link link-dark'
  li.nav-item
    = active_link_to t('.deleted'), archive_products_path, class: 'nav-link link-dark'

app/views/products/_product.html.slim
tr
  td = product.id
  td = link_to product.name, product_path(product)
  td = product.category.name
  td = product.price
  td = product.quantity
  td = l(product.created_at, format: :medium)

app/views/products/edit.html.slim
= turbo_frame_tag :modal do
  .modal-pop-app
    h1 = t('.editing_product')

    == render "form", product: @product

app/views/products/index.html.slim
h1 = t('navigation.products')

=render 'nav'

= link_to t('.add_product'), new_product_path, data: { turbo_frame: 'modal' },
        class: 'btn btn-primary' if current_page?(products_path)

- scope = 'activerecord.attributes.product'
table.table.table-striped.table-hover.mt-2
  thead
    th scope="col" = t('.id')
    th scope="col" = t('name', scope: scope)
    th scope="col" = t('category', scope: scope)
    th scope="col" = t('price', scope: scope)
    th scope="col" = t('quantity', scope: scope)
    th scope="col" = t('created_at', scope: scope)
  tbody
    = render @products

.d-flex.justify-content-center.mt-3
  = paginate @products

app/views/products/new.html.slim
= turbo_frame_tag :modal do
  .modal-pop-app
    h1 = t('.new_product')

    == render "form", product: @product

app/views/products/show.html.slim
= link_to t('global.button.back'), products_path, class: 'btn btn-secondary mb-2'

h1.mb-4
  = @product.name
.row
  .col-md-8
    .user-info
      - product_data = { t('.price') => @product.price,
                        t('.quantity') => @product.quantity,
                        t('.category') => @product.category.name,
                        t('.created_at') => l(@product.created_at, format: :medium) }

      - product_data.each do |label, value|
        .row.mb-2
          .col-6
            span = label
          .col-6.text-right
            = value

  .col-md-4.d-flex.justify-content-center
    .user-actions.d-flex.flex-column.w-auto
      - if @product.deleted_at
        = link_to t('global.button.restore'), restore_product_path(@product),
                data: { turbo_method: :patch }, class: 'btn btn-primary mb-1'
        - if can? :really_destroy, Product
          = link_to t('global.button.really_delete'), really_destroy_product_path(@product), class: 'btn btn-danger',
                  data: { turbo_method: :delete, confirm: t('global.dialog.you_sure') }
      - else
        = link_to t('global.button.edit'), edit_product_path(@product),
                data: { turbo_frame: 'modal', turbo_stream: true }, class: 'btn btn-primary mb-1'

        = link_to t('global.button.delete'), product_path(@product), class: 'btn btn-danger mb-1',
                  data: { turbo_method: :delete, confirm: t('global.dialog.you_sure') }

= image_tag(@product.image, style: 'width: 300px; height: auto') if @product.image.present?