config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users, controllers: {
      sessions: "users/sessions"
    }

    resources :mailings, only: %i[index] do
      collection do
        patch :update_settings, to: "mailings#update_settings", as: 'update_settings'
        get :settings, to: "mailings#settings", as: 'settings'
      end
    end

    resources :reports, only: %i[index] do
      collection do
        get :users, to: "reports#users_reports", as: 'users'
      end
    end

    resources :orders, except: %i[edit update] do
      collection do
        get :archive
        post 'create_for_product/:product_id', to: 'orders#create_for_product', as: :create_for_product
        delete 'delete_last', to: 'orders#delete_last', as: :delete_last
        get 'users', to: 'orders#users', as: :users
      end
    end
    resources :categories, except: %i[show edit update]
    resources :products do
      collection do
        get :archive
      end
      member do
        patch :restore
        delete :really_destroy
      end
    end

    resources :users, except: %i[new create] do
      member do
        patch :restore
        delete :really_destroy
        patch :approve

        get 'payment', to: 'user_payments#payment', as: 'payment'
        post 'payment/deposit_money', to: 'user_payments#deposit_money', as: 'deposit_money'
        post 'payment/pay_all_orders', to: 'user_payments#pay_all_orders', as: 'pay_all_orders'
        post 'payment/pay_order/:id', to: 'user_payments#pay_order', as: 'pay_order'
      end
      collection do
        get :requests
        get :archive
        patch :approve_all
        delete :delete_all
      end
    end

    resources :store, only: [:index], controller: 'telegram/store'

    # Маршруты для аутентификации через Telegram
    resource :telegram_session, only: [:new, :create], controller: 'telegram/sessions'

    telegram_webhook Telegram::TelegramWebhooksController

    # Defines the root path route ("/")
    root to: 'telegram/store#index'
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  authorize_resource class: false
  before_action :merge_date_filter_params

  has_scope :filter_by_username, as: :user
  has_scope :filter_by_date, using: %i[date_start date_end], as: :date
  has_scope :filter_by_state, as: :state
  has_scope :filter_by_product, as: :product

  def index
    @orders = apply_scopes(Order).includes(:user, :payment, :product).page(params[:page]).per(8)

    @price_orders = @orders.sum { |el| el.payment.amount }
    @count_orders = @orders.count
  end

  def users_reports
    @users = apply_scopes(User).approved
                               .joins(orders: :payment)
                               .group('users.id')
                               .select('users.*, SUM(payments.amount) AS total_price, COUNT(orders.id) AS total_count')
                               .order(id: :desc)
                               .page(params[:page]).per(8)

    @price_orders = @users.sum(&:total_price)
    @count_orders = @users.sum(&:total_count)
  end

  private

  def merge_date_filter_params
    params.merge! DateFilterService.prepare_date_filter_params(params[:start_date_between])
  end
end

app/views/reports/_filter.html.slim
= form_with url: path, method: :get, local: true, data: { controller: 'debounce', debounce_target: 'form',
        turbo_stream: true} do |f|
  .row
    .col-md-6
      .mb-3
        = f.search_field :user, value: params[:user], class: 'form-control form-control-lg', placeholder: t('.user')
    .col-md-6
      .mb-3
        = f.text_field :start_date_between, value: params[:start_date_between],
                data: { controller: "daterange-picker", user_payments_target: 'dateField' },
                class: 'form-control form-control-lg', placeholder: t('.date')
  .row
    .col-md-6
      .mb-3
        = f.select :state, payment_states,
          { include_blank: t('.all_status'), selected: params[:state], class: 'form-select form-select-lg'},
          { data: { controller: 'select' } }
    - unless current_page?(users_reports_path)
      .col-md-6
        .mb-3
          = f.select :product, Product.pluck(:name, :id), { include_blank: t('.all_product'), selected: params[:product],
                  class: 'form-select form-select-lg' },
                  { data: { controller: 'select' } }

  = f.submit t('global.button.filter'), class: 'btn btn-primary'

app/views/reports/_nav.html.slim
ul.nav.nav-tabs.mb-4
  li.nav-item
    = active_link_to t('.general_report'), reports_path, class: 'nav-link link-dark'
  li.nav-item
    = active_link_to t('.user_report'), users_reports_path, class: 'nav-link link-dark'

app/views/reports/_order.html.slim
tr
  td = order.user.decorate.name_with_sign
  td = order.product.name
  td = order.payment.amount
  td = 1
  td = t("activerecord.attributes.payment.#{order.payment.state}")

app/views/reports/_user_summaries.html.slim
tr
  td = user_summary.decorate.name_with_sign
  td = user_summary.deposit
  td = user_summary.total_price
  td = user_summary.total_count
  - state = Payment.states.key(params[:state].to_i)
  td = params[:state] ? t("activerecord.attributes.payment.#{state}") : t("activerecord.attributes.payment.all")
  td
    .btn-group
      = link_to t('.fully_paid'), pay_all_orders_user_path(user_summary),
              class: 'btn btn-primary', data: { turbo: false, action: 'user-payments#submitWithDate' }
      = link_to t('.enter_transfer_manually'), payment_user_path(user_summary),
              class: 'btn btn-secondary', data: { turbo_frame: :modal }

app/views/reports/index.html.slim
h1.mb-3 = t('navigation.reports')

= render 'nav'

= turbo_frame_tag 'reports' do
  = render 'filter', path: reports_path

  table.table.table-striped.table-hover.mt-2
    thead
      th scope="col" = t('reports.filter.user')
      th scope="col" = t('reports.filter.product')
      th scope="col" = t('reports.filter.cost')
      th scope="col" = t('reports.filter.quantity')
      th scope="col" = t('reports.filter.paid')
    tbody
      = render partial: 'reports/order', collection: @orders
    tfoot
      tr.table-active
        td.colspan-2 Итого
        td
        td = @price_orders
        td = @count_orders
        td

  .d-flex.justify-content-center.mt-3
    = paginate @orders

app/views/reports/users_reports.html.slim
h1.mb-3 = t('navigation.reports')

= render 'nav'

div data-controller="user-payments"
  = render 'filter', path: users_reports_path

  table.table.table-striped.table-hover.mt-2
    thead
      th scope="col" = t('reports.filter.user')
      th scope="col" = t('reports.filter.deposit')
      th scope="col" = t('reports.filter.cost')
      th scope="col" = t('reports.filter.quantity')
      th scope="col" = t('reports.filter.paid')
      th scope="col"
    tbody
      = render partial: 'reports/user_summaries', collection: @users, as: :user_summary
    tfoot
      tr.table-active
        td.colspan-2 Итого
        td
        td = @price_orders
        td = @count_orders
        td
        td

  .d-flex.justify-content-center.mt-3
    = paginate @users